## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy* 

**1.** Import pandas under the name `pd`.

In [250]:
from itertools import groupby
from json.decoder import NaN

import pandas as pd
import numpy as np
from jupyter_core.migrate import regex
from numpy.ma.core import size
from pandas import isnull

**2.** Print the version of pandas that has been imported.

In [251]:
pd.__version__

'3.0.2'

**3.** Print out all the version information of the libraries that are required by the pandas library.

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [252]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(data,labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Display a summary of the basic information about this DataFrame and its data.

In [253]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**6.** Return the first 3 rows of the DataFrame `df`.

In [254]:
df.iloc[0:3]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [255]:
df.loc[:,['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [256]:
df.loc[:,['animal','age']].iloc[[3,4,8]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Select only the rows where the number of visits is greater than 3.

In [257]:
df[df.visits>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**10.** Select the rows where the age is missing, i.e. is `NaN`.

In [258]:
df[df.age.isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [259]:
df[(df.animal=='cat') & (df.age<3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** Select the rows the age is between 2 and 4 (inclusive)

In [260]:
df[(df.age>=2)&(df.age<=4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** Change the age in row 'f' to 1.5.

In [261]:
df.loc['f','age']=1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**14.** Calculate the sum of all visits (the total number of visits).

In [262]:
df.visits.sum()

np.int64(19)

**15.** Calculate the mean age for each different animal in `df`.

In [263]:
df.groupby('animal').age.mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [264]:
a=pd.Series({'animal': 'ido',
        'age': 3,
        'visits': 0,
        'priority': 'maybe'})
df.loc['k',:]=a
df=df.drop(index='k')
df

  animal  age  visits priority
a    cat  2.5     1.0      yes
b    cat  3.0     3.0      yes
c  snake  0.5     2.0       no
d    dog  NaN     3.0      yes
e    dog  5.0     2.0       no
f    cat  1.5     3.0       no
g  snake  4.5     1.0       no
h    cat  NaN     1.0      yes
i    dog  7.0     2.0       no
j    dog  3.0     1.0       no

**17.** Count the number of each type of animal in `df`.

In [265]:
df.groupby('animal').count()

        age  visits  priority
animal
cat       3       4         4
dog       3       4         4
snake     2       2         2

**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visit' column in *ascending* order.

In [266]:
df=df.sort_values(by='age',ascending=False)
df.sort_values(by='visits')

  animal  age  visits priority
g  snake  4.5     1.0       no
j    dog  3.0     1.0       no
a    cat  2.5     1.0      yes
h    cat  NaN     1.0      yes
c  snake  0.5     2.0       no
e    dog  5.0     2.0       no
i    dog  7.0     2.0       no
b    cat  3.0     3.0      yes
f    cat  1.5     3.0       no
d    dog  NaN     3.0      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [267]:
df.priority=df.priority.astype('object')
df.loc[df.priority=='no','priority']=False
df.loc[df.priority=='yes','priority']=True
df.priority=df.priority.astype('bool')

df

  animal  age  visits  priority
i    dog  7.0     2.0     False
e    dog  5.0     2.0     False
g  snake  4.5     1.0     False
b    cat  3.0     3.0      True
j    dog  3.0     1.0     False
a    cat  2.5     1.0      True
f    cat  1.5     3.0     False
c  snake  0.5     2.0     False
d    dog  NaN     3.0      True
h    cat  NaN     1.0      True

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [268]:
df.loc[df.animal=='snake','animal']='python'
df

   animal  age  visits  priority
i     dog  7.0     2.0     False
e     dog  5.0     2.0     False
g  python  4.5     1.0     False
b     cat  3.0     3.0      True
j     dog  3.0     1.0     False
a     cat  2.5     1.0      True
f     cat  1.5     3.0     False
c  python  0.5     2.0     False
d     dog  NaN     3.0      True
h     cat  NaN     1.0      True

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (hint: use a pivot table).

In [269]:
df.pivot_table(values='age',index='animal',columns='visits')

visits  1.0  2.0   3.0
animal
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
python  4.5  0.5   NaN

### query()

Now do 11 again, this time using the DataFrame.query() method.

In [270]:
df[(df.animal=='cat') & (df.age<3)]
df.query('animal=="cat" & age<3')

  animal  age  visits  priority
a    cat  2.5     1.0      True
f    cat  1.5     3.0     False

Try doing question 12 using the DataFrame.query() method.

In [271]:
df[(df.age>=2)&(df.age<=4)]
df.query('age>=2 & age<=4')

  animal  age  visits  priority
b    cat  3.0     3.0      True
j    dog  3.0     1.0     False
a    cat  2.5     1.0      True

Now, try creating a function get_range() that gets in input a dataframe and two values and gives back every animal whose age is between these two values. Check it with the values of question 12.

In [272]:
def get_range(df,vals):
    return(df[(df.age>=vals[0])&(df.age<=vals[1])])
get_range(df,[2,4])

  animal  age  visits  priority
b    cat  3.0     3.0      True
j    dog  3.0     1.0     False
a    cat  2.5     1.0      True

Now, create a function get_animals() that receives a dataframe and two animal names and return all the animals of the two given types in the dataframe, using query(). Check it with cat and snake.

In [273]:
def get_animals(df,animals):
    return(df[(df.animal==animals[0])|(df.animal==animals[1])])
get_animals(df,['cat','python'])

   animal  age  visits  priority
g  python  4.5     1.0     False
b     cat  3.0     3.0      True
a     cat  2.5     1.0      True
f     cat  1.5     3.0     False
c  python  0.5     2.0     False
h     cat  NaN     1.0      True

Try doing the get_range question, this time using the python format() method for strings.

In [274]:
def get_range(df,vals):
    return(df.query('age>={0} & age<={1}'.format(vals[0],vals[1])))
get_range(df,[2,4])

  animal  age  visits  priority
b    cat  3.0     3.0      True
j    dog  3.0     1.0     False
a    cat  2.5     1.0      True

## DataFrames: using complicated functions

Difficulty: *medium*

here you will be asked to generate your own test data and manipulate it using functions you will have to create.

**22.** Create a dataframe with 1000 rows and 3 columns. The columns are to be the following:
        - age: an integer, uniformly distributed between 20 to 65
        - skill: a float, normally distributed between 0 and 1, with expected value = 0.5 and standard deviation = 0.3
        - height: a float with 2 digits after the decimal point, between 1.5 to 2.0
you might want to use numpy.random

In [275]:
age=np.random.randint(20,65,1000)
skill=np.random.normal(0.5,0.3,1000).clip(0,1)
height=np.random.uniform(1.5,2,1000).round(decimals=2)
data={'age':age,'skill':skill,'height':height}
df=pd.DataFrame(data)
df.head()

   age     skill  height
0   36  0.813669    1.63
1   43  0.692407    1.53
2   33  1.000000    1.64
3   64  1.000000    1.72
4   53  0.272361    1.81

**23.** Add the dataframe a new columns, called salary, when:
        salary = 1000*((age^2)/1000 + 1.7*skill + 0.4*exp(-(height-1.7)**2)

In [276]:
salary=1000*(age**2/1000)+1.7*skill+0.4*np.exp(-(height-1.7)**2)
df["salary"]=salary
df.head()

   age     skill  height       salary
0   36  0.813669    1.63  1297.781281
1   43  0.692407    1.53  1850.565697
2   33  1.000000    1.64  1091.098563
3   64  1.000000    1.72  4098.099840
4   53  0.272361    1.81  2809.858202

**24.** Split the dataframe to groups by the age left digit and by the age. for each group compute:
        - the number of rows
        - the mean salary
        - the maximum height

In [277]:
# print(df.groupby('age').mean().salary)
# print(df.groupby('age').max().salary)
print(df.groupby(df.age//10).mean().salary)
print(df.groupby(df.age//10).max().salary)

age
2     601.070092
3    1206.744519
4    1980.794338
5    2990.533149
6    3833.100978
Name: salary, dtype: float64
age
2     843.095189
3    1522.795699
4    2402.831516
5    3483.099640
6    4098.099840
Name: salary, dtype: float64

**25.** Now split the dataframe to groups by age. for each group compute the mean salary, split by the sum of heights.

In [278]:
df.groupby('age').mean() #didnt understand

        skill    height       salary
age
20   0.449289  1.748636   401.156067
21   0.543759  1.747600   442.316899
22   0.479830  1.767200   485.205720
23   0.430195  1.690500   530.124445
24   0.584698  1.751429   577.383299
25   0.551292  1.785455   626.328369
26   0.509231  1.808750   677.253137
27   0.444473  1.717000   730.145924
28   0.394159  1.733889   785.062538
29   0.539262  1.720417   842.308958
30   0.617420  1.704000   901.440727
31   0.606687  1.720357   962.423713
32   0.455857  1.725455  1025.165583
33   0.400025  1.759565  1090.070374
34   0.559418  1.770435  1157.339331
35   0.488660  1.752381  1226.221997
36   0.501566  1.770000  1297.243634
37   0.513478  1.746786  1370.265541
38   0.477827  1.714583  1445.202036
39   0.460414  1.779048  1522.174201
40   0.495541  1.758947  1601.235050
41   0.450547  1.795294  1682.154754
42   0.424730  1.731429  1765.114206
43   0.492866  1.761176  1850.228235
44   0.439714  1.708519  1937.139003
45   0.511130  1.710588  2026.262075
46   0.508077  1.704000  2117.255030
47   0.426046  1.773158  2210.118039
48   0.604836  1.701905  2305.419454
49   0.424068  1.720455  2402.114410
50   0.462054  1.756667  2501.176459
51   0.458031  1.756364  2602.167960
52   0.384621  1.810000  2705.044143
53   0.503102  1.732500  2810.247495
54   0.585304  1.714348  2917.387166
55   0.613472  1.733913  3026.432867
56   0.550287  1.765000  3137.323114
57   0.590544  1.785882  3250.391719
58   0.459397  1.763871  3365.172012
59   0.555411  1.745833  3482.337900
60   0.500789  1.753871  3601.242698
61   0.495757  1.672727  3722.239230
62   0.557023  1.737333  3845.338804
63   0.471095  1.771379  3970.191250
64   0.529932  1.773000  4097.291600

**26.** Add these lines to your code:

        import matplotlib.pyplot as plt
        %matplotlib inline
        
Now try using the pd.DataFrame.plot function to show your data. Try also using pd.DataFrame.boxplot.

In [279]:
import matplotlib.pyplot as plt
%matplotlib inline

**27.** Save the result as a csv, then read the csv to the variable "data" using pandas

In [280]:
df.to_csv('data.csv')
df=pd.read_csv('data.csv')

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**28.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

In [281]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
L=df.size
is_same=np.array(df.iloc[0:-1]["A"].values!=df.iloc[1:]["A"].values)
df.iloc[1:][is_same]

   A
1  2
3  3
4  4
5  5
8  6
9  7

**29.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [282]:
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
means=df.mean(axis=1)
df.sub(means,axis=0)

          0         1         2
0  0.116314 -0.126578  0.010264
1  0.139095  0.020359 -0.159454
2  0.017770 -0.322949  0.305179
3  0.066902  0.134692 -0.201594
4  0.200999 -0.009965 -0.191034

**30.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum? (Find that column's label.)

In [283]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
df.sum(axis=0).idxmin()

'i'

**31.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)?

In [284]:
df=pd.DataFrame({'a':[1,2,1],'b':[2,2,2]})
df.drop_duplicates()

   a  b
0  1  2
1  2  2

The next three puzzles are slightly harder...

**32.** You have a DataFrame that consists of 10 columns of floating--point numbers. Suppose that exactly 5 entries in each row are NaN values. For each row of the DataFrame, find the *column* which contains the *third* NaN value.

(You should return a Series of column labels.)

In [285]:
df=pd.DataFrame(np.random.permutation(np.sqrt(np.arange(-5,5))).reshape(1,10))
third_nan_idx=df.isna().cumsum(axis=1)==3
third_nan_idx
print(third_nan_idx.idxmax(axis=1))

0    4
dtype: int64

C:\Users\USER\AppData\Local\Temp\ipykernel_20936\3386533631.py:1: RuntimeWarning: invalid value encountered in sqrt
  df=pd.DataFrame(np.random.permutation(np.sqrt(np.arange(-5,5))).reshape(1,10))

**33.** A DataFrame has a column of groups 'grps' and and column of numbers 'vals'. For example: 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values.

In [286]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
df
df.groupby('grps')['vals'].nlargest(3).groupby(level=0).sum()

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**34.** A DataFrame has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

In [287]:
A=np.random.randint(1,100,size=1000)
B=np.random.randint(10,size=1000)
df=pd.DataFrame({'A':A,'B':B})
df.groupby((df['A']-1)//10).B.sum()

A
0    490
1    491
2    394
3    393
4    495
5    478
6    449
7    357
8    400
9    500
Name: B, dtype: int32

## DataFrames: harder problems 

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**35.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be `[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]`. Make this a new column 'Y'.

In [288]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
zero_idxs=np.arange(len(df))[df['X'].isin([0])]
zero_idxs=np.append(0,zero_idxs)
dist_from_zero=np.arange(len(df))[:,np.newaxis]-zero_idxs[np.newaxis,:]
dist_from_zero[dist_from_zero<0]=len(df)
dist_from_zero=np.min(dist_from_zero,axis=1)

df['Y']=dist_from_zero
df

   X  Y
0  7  0
1  2  1
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

**36.** Consider a DataFrame containing rows and columns of purely numerical data. Create a list of the row-column index locations of the 3 largest values.

In [289]:
df=pd.DataFrame(np.random.random(size=[10,5]))
df.unstack().nlargest(3).index

MultiIndex([(3, 7),
            (3, 1),
            (3, 2)],
           )

**37.** Given a DataFrame with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals', replace any negative values in 'vals' with the group mean.

In [290]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,-3,1,45,14,4,52,-54,-23,235,-21,57,3,87]})
mask=df.vals<0
# df["vals"][df.vals<0]=df.groupby('grps')['vals'].mean()
df['vals']=df['vals'].astype('float')
means=df[~mask].groupby('grps')['vals'].mean()
df.loc[mask,'vals'] = df.loc[mask,'grps'].map(means)
df

   grps    vals
0     a   12.00
1     a  345.00
2     a  103.25
3     b    1.00
4     b   45.00
5     c   14.00
6     a    4.00
7     a   52.00
8     b   26.50
9     c  112.00
10    c  235.00
11    c  112.00
12    b   57.00
13    b    3.00
14    c   87.00

**38.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, 
                                 np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

In [291]:
df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3,
                                 np.nan, 1, 7, 3, np.nan, 8]})

a=df.groupby('group',as_index=False)['value'].rolling(3,min_periods=1).mean()
a.sort_index()

   group     value
0      a  1.000000
1      a  1.500000
2      b  3.000000
3      b  3.000000
4      a  1.666667
5      b  3.000000
6      b  3.000000
7      b  2.000000
8      a  3.666667
9      b  2.000000
10     a  4.500000
11     b  4.000000

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.

**39.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [292]:
dates=pd.bdate_range(start='2015-01-01',end='2015-12-31')
s=pd.Series(np.random.random(len(dates)),index=dates)
s

2015-01-01    0.333848
2015-01-02    0.661030
2015-01-05    0.525304
2015-01-06    0.059566
2015-01-07    0.525358
                ...
2015-12-25    0.133133
2015-12-28    0.569685
2015-12-29    0.993801
2015-12-30    0.072919
2015-12-31    0.348840
Freq: B, Length: 261, dtype: float64

**40.** Find the sum of the values in `s` for every Wednesday.

In [293]:
s[s.index.weekday==3].sum()

np.float64(27.52468005805258)

**41.** For each calendar month in `s`, find the mean of values.

In [294]:
s.groupby(s.index.month).mean()
a

   group     value
0      a  1.000000
1      a  1.500000
4      a  1.666667
8      a  3.666667
10     a  4.500000
2      b  3.000000
3      b  3.000000
5      b  3.000000
6      b  3.000000
7      b  2.000000
9      b  2.000000
11     b  4.000000

**42.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [295]:
max_idxs=s.groupby(s.index.month).idxmax()
maxs=s.groupby(s.index.month).max()
# a.
max_months=maxs.rolling(4,min_periods=1).max()#.apply(np.argmax).values+np.arange(12)
max_idxs[max_months==maxs]

1    2015-01-08
4    2015-04-02
5    2015-05-07
6    2015-06-23
7    2015-07-28
12   2015-12-29
dtype: datetime64[us]

**43.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [296]:
third_thursdays = pd.date_range(start='2015-01-01', end='2015-12-31', freq='WOM-3THU')
third_thursdays

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17'],
              dtype='datetime64[us]', freq='WOM-3THU')

## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
(It's some flight data I made up; it's not meant to be accurate in any way.)

**44.** Some values in the the FlightNumber column are missing. These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Fill in these missing numbers and make the column an integer column (instead of a float column).

In [297]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df['FlightNumber']=df['FlightNumber'].interpolate().astype('int')
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

**45.** The From\_To column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame with the correct values. Assign the correct column names to this temporary DataFrame.

In [298]:
a=df['From_To'].str.split('_')
a=pd.DataFrame(a.tolist(),columns=['from','to'])
a

       from         to
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**46.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [299]:
a['from']=a['from'].str.capitalize()
a['to']=a['to'].str.capitalize()
a

       from         to
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**47.** Delete the From_To column from `df` and attach the temporary DataFrame from the previous questions.

In [300]:
df.drop(columns='From_To',inplace=True)
df=pd.concat([df,a],axis=1)
df

   FlightNumber  RecentDelays              Airline      from         to
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London

**48**. In the Airline column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [301]:
df['Airline']=df['Airline'].str.replace(r'[^a-zA-Z\s]','',regex=True).str.strip()
df

   FlightNumber  RecentDelays          Airline      from         to
0         10045      [23, 47]              KLM    London      Paris
1         10055            []       Air France    Madrid      Milan
2         10065  [24, 43, 87]  British Airways    London  Stockholm
3         10075          [13]       Air France  Budapest      Paris
4         10085      [67, 32]        Swiss Air  Brussels     London

**49**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [302]:
delays_len = pd.Series(df['RecentDelays']).apply(len)
delays = pd.Series(df['RecentDelays']).to_numpy()
delays_array=np.full([len(delays),max(delays_len)],np.nan)
mask=np.arange(max(delays_len))[np.newaxis,:]<delays_len.to_numpy()[:,np.newaxis]
delays_array[mask]=np.concatenate(delays)
df["delay_1"]=delays_array[:,0]
df["delay_2"]=delays_array[:,1]
df["delay_3"]=delays_array[:,2]
df

,FlightNumber,RecentDelays,Airline,from,to,delay_1,delay_2,delay_3
0,10045,"[23, 47]",KLM,London,Paris,23.0,47.0,NaN
1,10055,[],Air France,Madrid,Milan,NaN,NaN,NaN
2,10065,"[24, 43, 87]",British Airways,London,Stockholm,24.0,43.0,87.0
3,10075,[13],Air France,Budapest,Paris,13.0,NaN,NaN
4,10085,"[67, 32]",Swiss Air,Brussels,London,67.0,32.0,NaN

The DataFrame should look much better now.

## Using MultiIndexes

### Go beyond flat DataFrames with additional index levels

Difficulty: *medium*

Previous exercises have seen us analysing data from DataFrames equipped with a single index level. However, pandas also gives you the possibilty of indexing your data using *multiple* levels. This is very much like adding new dimensions to a Series or a DataFrame. For example, a Series is 1D, but by using a MultiIndex with 2 levels we gain of much the same functionality as a 2D DataFrame.

The set of puzzles below explores how you might use multiple index levels to enhance data analysis.

To warm up, we'll look make a Series with two index levels.

**50**. Given the lists `letters = ['A', 'B', 'C']` and `numbers = list(range(10))`, construct a MultiIndex object from the product of the two lists. Use it to index a Series of random numbers. Call this Series `s`.

In [303]:
letters = ['A', 'B', 'C']
numbers = list(range(10))
a=pd.MultiIndex.from_product([letters,numbers])
s=pd.Series(np.random.random(len(letters)*len(numbers)),a)
s

A  0    0.323073
   1    0.564919
   2    0.076709
   3    0.561032
   4    0.859956
   5    0.733062
   6    0.815163
   7    0.220499
   8    0.543017
   9    0.780732
B  0    0.303671
   1    0.853297
   2    0.433162
   3    0.939702
   4    0.811038
   5    0.323520
   6    0.505934
   7    0.444368
   8    0.879212
   9    0.952092
C  0    0.268071
   1    0.364247
   2    0.605840
   3    0.694250
   4    0.682880
   5    0.696286
   6    0.290672
   7    0.738462
   8    0.229059
   9    0.041985
dtype: float64

**51.** Check the index of `s` is lexicographically sorted (this is a necessary proprty for indexing to work correctly with a MultiIndex).

In [304]:
s.index._is_lexsorted()

True

**52**. Select the labels `1`, `3` and `6` from the second level of the MultiIndexed Series.

In [305]:
s.loc[:,[1,3,6]]

A  1    0.564919
   3    0.561032
   6    0.815163
B  1    0.853297
   3    0.939702
   6    0.505934
C  1    0.364247
   3    0.694250
   6    0.290672
dtype: float64

**53**. Slice the Series `s`; slice up to label 'B' for the first level and from label 5 onwards for the second level.

In [306]:
s.loc[:'B',5:]

A  5    0.733062
   6    0.815163
   7    0.220499
   8    0.543017
   9    0.780732
B  5    0.323520
   6    0.505934
   7    0.444368
   8    0.879212
   9    0.952092
dtype: float64

**54**. Sum the values in `s` for each label in the first level (you should have Series giving you a total for labels A, B and C).

In [307]:
s.groupby(level=0).sum()

A    5.478162
B    6.445997
C    4.611752
dtype: float64

**55**. Suppose that `sum()` (and other methods) did not accept a `level` keyword argument. How else could you perform the equivalent of `s.sum(level=1)`?

In [320]:
s.reset_index().groupby('level_1').sum() # it does sum based on the first level
s

A  0    0.323073
   1    0.564919
   2    0.076709
   3    0.561032
   4    0.859956
   5    0.733062
   6    0.815163
   7    0.220499
   8    0.543017
   9    0.780732
B  0    0.303671
   1    0.853297
   2    0.433162
   3    0.939702
   4    0.811038
   5    0.323520
   6    0.505934
   7    0.444368
   8    0.879212
   9    0.952092
C  0    0.268071
   1    0.364247
   2    0.605840
   3    0.694250
   4    0.682880
   5    0.696286
   6    0.290672
   7    0.738462
   8    0.229059
   9    0.041985
dtype: float64

**56**. Exchange the levels of the MultiIndex so we have an index of the form (letters, numbers). Is this new Series properly lexsorted? If not, sort it.

In [309]:
s.swaplevel(0,1).sort_index()

0  A    0.323073
   B    0.303671
   C    0.268071
1  A    0.564919
   B    0.853297
   C    0.364247
2  A    0.076709
   B    0.433162
   C    0.605840
3  A    0.561032
   B    0.939702
   C    0.694250
4  A    0.859956
   B    0.811038
   C    0.682880
5  A    0.733062
   B    0.323520
   C    0.696286
6  A    0.815163
   B    0.505934
   C    0.290672
7  A    0.220499
   B    0.444368
   C    0.738462
8  A    0.543017
   B    0.879212
   C    0.229059
9  A    0.780732
   B    0.952092
   C    0.041985
dtype: float64

## Minesweeper

### Generate the numbers for safe squares in a Minesweeper grid

Difficulty: *medium* to *hard*

If you've ever used an older version of Windows, there's a good chance you've played with [Minesweeper](https://en.wikipedia.org/wiki/Minesweeper_(video_game). If you're not familiar with the game, imagine a grid of squares: some of these squares conceal a mine. If you click on a mine, you lose instantly. If you click on a safe square, you reveal a number telling you how many mines are found in the squares that are immediately adjacent. The aim of the game is to uncover all squares in the grid that do not contain a mine.

In this section, we'll make a DataFrame that contains the necessary data for a game of Minesweeper: coordinates of the squares, whether the square contains a mine and the number of mines found on adjacent squares.

**57**. Let's suppose we're playing Minesweeper on a 5 by 4 grid, i.e.
```
X = 5
Y = 4
```
To begin, generate a DataFrame `df` with two columns, `'x'` and `'y'` containing every coordinate for this grid. That is, the DataFrame should start:
```
   x  y
0  0  0
1  0  1
2  0  2
```

In [310]:
y,x=np.meshgrid(np.arange(4),np.arange(5))
df=pd.DataFrame({'x':x.flatten(),'y':y.flatten()})

**58**. For this DataFrame `df`, create a new column of zeros (safe) and ones (mine). The probability of a mine occuring at each location should be 0.4.

In [311]:
mines=np.random.binomial(1,0.4,20)
df['mines']=mines
df

    x  y  mines
0   0  0      1
1   0  1      0
2   0  2      1
3   0  3      1
4   1  0      1
5   1  1      0
6   1  2      1
7   1  3      0
8   2  0      1
9   2  1      1
10  2  2      1
11  2  3      0
12  3  0      0
13  3  1      0
14  3  2      0
15  3  3      0
16  4  0      1
17  4  1      0
18  4  2      0
19  4  3      0

**59**. Now create a new column for this DataFrame called `'adjacent'`. This column should contain the number of mines found on adjacent squares in the grid. 

(E.g. for the first row, which is the entry for the coordinate `(0, 0)`, count how many mines are found on the coordinates `(0, 1)`, `(1, 0)` and `(1, 1)`.)

In [312]:
mines=df['mines'].values.reshape(5,4)
neighbours=np.zeros(mines.shape)
neighbours+=np.pad(mines[0:-1,0:-1],pad_width=[(1,0),(1,0)])
neighbours+=np.pad(mines[0:-1,:],pad_width=[(1,0),(0,0)])
neighbours+=np.pad(mines[0:-1,1:],pad_width=[(1,0),(0,1)])
neighbours+=np.pad(mines[1:,0:-1],pad_width=[(0,1),(1,0)])
neighbours+=np.pad(mines[1:,:],pad_width=[(0,1),(0,0)])
neighbours+=np.pad(mines[1:,1:],pad_width=[(0,1),(0,1)])
neighbours+=np.pad(mines[:,0:-1],pad_width=[(0,0),(1,0)])
neighbours+=np.pad(mines[:,1:],pad_width=[(0,0),(0,1)])
df['adjacent']=neighbours.flatten()

**60**. For rows of the DataFrame that contain a mine, set the value in the `'adjacent'` column to NaN.

In [313]:
df.loc[df['mines']==1,'adjacent']=np.nan
df

    x  y  mines  adjacent
0   0  0      1       NaN
1   0  1      0       4.0
2   0  2      1       NaN
3   0  3      1       NaN
4   1  0      1       NaN
5   1  1      0       7.0
6   1  2      1       NaN
7   1  3      0       4.0
8   2  0      1       NaN
9   2  1      1       NaN
10  2  2      1       NaN
11  2  3      0       2.0
12  3  0      0       3.0
13  3  1      0       4.0
14  3  2      0       2.0
15  3  3      0       1.0
16  4  0      1       NaN
17  4  1      0       1.0
18  4  2      0       0.0
19  4  3      0       0.0

**61**. Finally, convert the DataFrame to grid of the adjacent mine counts: columns are the `x` coordinate, rows are the `y` coordinate.

In [330]:
df=df.sort_values(['x','y'])
df['adjacent'].to_numpy().reshape(5,4)

array([[nan,  4., nan, nan],
       [nan,  7., nan,  4.],
       [nan, nan, nan,  2.],
       [ 3.,  4.,  2.,  1.],
       [nan,  1.,  0.,  0.]])